spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=TRUE;MODE=MySQL
    username: sa
    password:
    initialization-mode=always:jpa:
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.ykmura.springmybatisencrypt.typehandler
caesar-cipher:
  shift: 3
